- from:
      entity: environment
      to_attribute_name: environment
      to_display_name: "$this->name"
      to_snaps:
          environment:
              - name
  to:
      entity: host
      from_attribute_name: hosts
      from_display_name: "$this->name.' '.$this->ip"
      from_snaps: []
  relationship_type: has_many
  association_type: aggregation
